safe: true
lsi: false
pygments: true
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class
source: .
destination: ./_site
permalink: /examples/:title
exclude: ['README.md', '.gitignore']
name: turf in mapbox.js
baseurl: /turf-www
description: examples of turfjs using mapbox.js
url: http://rousseau.io/turf-www
